{% set name = "prms_surface" %}
{% set version = "0.2" %}
{% set release = "beta" %}
{% set build_number = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/nhm-usgs/bmi-prms6-surface
  git_rev: 5e3e455be9cbd8ef15d6c57b065c94478acf8401

build:
  string: {{ release }}_{{ build_number }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('fortran') }}
    - libnetcdf
    - netcdf-fortran
  host:
    - libnetcdf
    - netcdf-fortran
    - coretran
    - prms
  run:
    - libnetcdf
    - netcdf-fortran
    - coretran
    - prms

test:
  commands:
    - test -s $PREFIX/lib/libbmiprmssurface$SHLIB_EXT
    - test -s $PREFIX/include/bmif_2_0.mod
    - test -s $PREFIX/include/bmiprmssurface.mod

about:
  home: https://www.usgs.gov/software/precipitation-runoff-modeling-system-prms
  license: CCO 1.0 Universal
  license_file: License.md
  summary: USGS Precipitation Runoff Modeling System (PRMS) Surface component
  description: |
    The Precipitation-Runoff Modeling System (PRMS) is a
    deterministic, distributed-parameter, physical process based
    modeling system developed to evaluate the response of various
    combinations of climate and land use on streamflow and general
    watershed hydrology. This version of PRMS has been
    refactored to use only the surface water component, and it is
    equipped with a Basic Model Interface.
  dev_url: https://github.com/nhm-usgs/bmi-prms6-surface
