language: generic

os:
  - linux
  - osx

env:
  global:
    - CONDA_PREFIX=$HOME/conda
    - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
    - TRAVIS_PYTHON_VERSION="3.*"
    - secure: "2qOfKEuO0icsmELQ3CGbecDfa5NUdsPYRdxG3FtPvPaY8Tir1c/B2Zv0KCO4vD7/b8Qss144lJdQDnpLEBXrXiaJxBgUEe27aFBsp8VFpr+0bA/DS2JrqOemOwWSGcTWL7M1xOyRZK4BpVxlLjkK1CNfzUfpt0gMmTSGuIzhW0l/1jaPVGs1M1I70ec+RNGnovi7mI4PPvq5LDSaAU/V1mMkciQJh3g5DKAHZe3E/PtiOubv6qrnvkwzhbbzPybgayaoyxuzEeRO0MxHzWor68YgBD1+ui9D3u1GbEiBJX+vF8CEdrN3sjxTYgiahxiWCkR4ZYWSCmWhex4XDm6GYJMuh8Amauz+xpOFk8WsfbTyOHiPq7b4SqvHBiN5W0LX8oETdTUqiRJN3eRyNkfmk3glCmoXgD8EZBBqBGnsXIeX0Z5B7yMs4BIcqDSbkMflrxKgVMDVI2jN3+oTFwlVT73ZT5pecclWd1gbXqQRV7pb6D1FECi2VA+5FeJNvxPtUxiY1E4i2+Mj3GwzbEZ2l0jPy3ud49wL/sNHPYZ8iXFKqaJko7G5LES7PWOG2QqXsjOTBjdGQFzqeZLPqj7FhCiHEpDzooS0Y7YVH8aZqGsZl3fFKJx6jEyrylBXoQniNWSu/4oNunN9ydPwCWf/wTwRvLLD7P0TS5zuwRPspuk="

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      brew remove --force $(brew list)
      brew cleanup -s
      rm -rf $(brew --cache)
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install python=$TRAVIS_PYTHON_VERSION -c conda-forge
  - conda install -q conda-build anaconda-client -c conda-forge

script:
  - conda build ./recipe -c conda-forge -c csdms-stack --old-build-string

after_success:
  - curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
  - echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-
